stages:
  - build
  - deploy

build_page:
  stage: build
  image: registry.gitlab.com/gbraad/docugen:latest
  script:
    - git clone https://gitlab.com/gbraad/document-generation-assets.git assets --depth 1
    - mkdir public
    - cp -r assets/public-content/reveal/* public/
    - pandoc -t html5 --template assets/templates/reveal-slides-template.html --standalone --section-divs ./index.md -o ./public/index.html
    - for f in ./[0-9]*.md; do pandoc -t html5 --template assets/templates/reveal-slides-template.html --standalone --section-divs $f -o ./public/${f/%.md}.html; done
    - for f in ./[0-9]*.md; do pandoc -V geometry:margin=1in $f -o ./public/${f/%.md}.pdf; done
    - cp -r img public/
  artifacts:
    paths:
    - public
  only:
  - master

pages:
  stage: deploy
  artifacts:
    paths:
      - public
  only:
    - master